/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface LoadingSpinner {}
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface SideDrawer {
    'headingTitle': string;
    'open': boolean;
    'openSideDrawer': () => Promise<void>;
  }
  interface StockFinder {}
  interface StockPrice {
    'inputStockSymbol': string;
  }
  interface ToolTip {
    'text': string;
  }
}

declare global {


  interface HTMLLoadingSpinnerElement extends Components.LoadingSpinner, HTMLStencilElement {}
  var HTMLLoadingSpinnerElement: {
    prototype: HTMLLoadingSpinnerElement;
    new (): HTMLLoadingSpinnerElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLSideDrawerElement extends Components.SideDrawer, HTMLStencilElement {}
  var HTMLSideDrawerElement: {
    prototype: HTMLSideDrawerElement;
    new (): HTMLSideDrawerElement;
  };

  interface HTMLStockFinderElement extends Components.StockFinder, HTMLStencilElement {}
  var HTMLStockFinderElement: {
    prototype: HTMLStockFinderElement;
    new (): HTMLStockFinderElement;
  };

  interface HTMLStockPriceElement extends Components.StockPrice, HTMLStencilElement {}
  var HTMLStockPriceElement: {
    prototype: HTMLStockPriceElement;
    new (): HTMLStockPriceElement;
  };

  interface HTMLToolTipElement extends Components.ToolTip, HTMLStencilElement {}
  var HTMLToolTipElement: {
    prototype: HTMLToolTipElement;
    new (): HTMLToolTipElement;
  };
  interface HTMLElementTagNameMap {
    'loading-spinner': HTMLLoadingSpinnerElement;
    'my-component': HTMLMyComponentElement;
    'side-drawer': HTMLSideDrawerElement;
    'stock-finder': HTMLStockFinderElement;
    'stock-price': HTMLStockPriceElement;
    'tool-tip': HTMLToolTipElement;
  }
}

declare namespace LocalJSX {
  interface LoadingSpinner {}
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface SideDrawer {
    'headingTitle'?: string;
    'open'?: boolean;
  }
  interface StockFinder {
    'onCurrentSymbolSelected'?: (event: CustomEvent<string>) => void;
  }
  interface StockPrice {
    'inputStockSymbol'?: string;
  }
  interface ToolTip {
    'text'?: string;
  }

  interface IntrinsicElements {
    'loading-spinner': LoadingSpinner;
    'my-component': MyComponent;
    'side-drawer': SideDrawer;
    'stock-finder': StockFinder;
    'stock-price': StockPrice;
    'tool-tip': ToolTip;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'loading-spinner': LocalJSX.LoadingSpinner & JSXBase.HTMLAttributes<HTMLLoadingSpinnerElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'side-drawer': LocalJSX.SideDrawer & JSXBase.HTMLAttributes<HTMLSideDrawerElement>;
      'stock-finder': LocalJSX.StockFinder & JSXBase.HTMLAttributes<HTMLStockFinderElement>;
      'stock-price': LocalJSX.StockPrice & JSXBase.HTMLAttributes<HTMLStockPriceElement>;
      'tool-tip': LocalJSX.ToolTip & JSXBase.HTMLAttributes<HTMLToolTipElement>;
    }
  }
}


